repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/necaris/pre-commit-pyright
    rev: "1.1.53"
    hooks:
      - id: pyright

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-yaml
      - id: check-json

  # https://github.com/zakhenry/embedme
  - repo: local
    hooks:
      - id: embed-code-to-readme
        name: embed-code-to-readme
        language: system
        entry: npx embedme README.md
        always_run: true
